server/webserver/copa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [url(r'^$', RedirectView.as_view(url='/monitor')),
               url(r'^admin/', admin.site.urls),
               url(r'^core/', include('core.urls')),
               url(r'^monitor/', include('monitor.urls')),
               url(r'^REST/network/', include('monitor.REST.urls')),
               url(r'^REST/', include('core.REST.urls')),
               url(r'^accounts/', include('django.contrib.auth.urls'))]

server/webserver/core/REST/urls.py
from django.conf.urls import url

from .functions import RestFunctions

# REST URLS
urlpatterns = [url(r"^pools$", RestFunctions.pool,
                   name="REST_pool"),
               url(r"^container$", RestFunctions.container,
                   name="REST_container"),
               url(r"^image$", RestFunctions.image,
                   name="REST_image"),
               ]

server/webserver/core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.index, name='index'),
    url(r'^welcome/$',
        views.welcome, name='welcome'),
    url(r'^orchestration/$',
        views.orchestration, name='orchestration'),
    url(r'^containers_list/$',
        views.containers_list, name='containers_list'),
    url(r'^containers_list/start/(?P<xhost>[\w\-]+)/(?P<container_name>[\w\-]+)$',
        views.containers_start, name='containers_start'),
    url(r'^containers_list/stop/(?P<xhost>[\w\-]+)/(?P<container_name>[\w\-]+)$',
        views.containers_stop, name='containers_stop'),
    url(r'^containers_list/delete/(?P<xhost>[\w\-]+)/(?P<container_name>[\w\-]+)$',
        views.containers_delete, name='containers_delete'),
    url(r'^containers_list/freeze/(?P<xhost>[\w\-]+)/(?P<container_name>[\w\-]+)$',
        views.containers_freeze, name='containers_freeze'),
    url(r'^containers_list/unfreeze/(?P<xhost>[\w\-]+)/(?P<container_name>[\w\-]+)$',
        views.containers_unfreeze, name='containers_unfreeze'),
    url(r'^containers_list/new/$',
        views.containers_new, name='containers_new'),
    url(r'^containers_list/add/$',
        views.containers_add, name='containers_new'),
    url(r'^containers_list/console/(?P<server>[\w\-]+)/(?P<container_name>[\w\-]+)$',
        views.containers_terminal, name='containers_terminal'),
    url(r'^containers_list/migrate/(?P<origin>[\w\-]+)/(?P<name_container>[\w\-]+)/(?P<destination>[\w\-]+)$',
        views.containers_migrate, name='containers_migrate'),
    url(r'^containers_list/info/(?P<xhost>[\w\-]+)/(?P<container_name>[\w\-]+)$',
        views.containers_info, name='containers_info'),
    url(r'^containers_list/api/$',
        views.api_execution, name='api_execution'),
]

server/webserver/core/models.py
from django.db import models

from django.urls import reverse


# Create your models here.
class Configuration(models.Model):
    name = models.CharField(max_length=50,
                            default="default",
                            editable=False,
                            primary_key=True,
                            help_text="Configuration name.")
    DELEGATION_CHOICES = (("a", "Automatic"),
                          ("m", "Manual"))
    delegation_mode = models.CharField(max_length=1,
                                       choices=DELEGATION_CHOICES,
                                       help_text="Delegation mode (a - "
                                                 "Automatic; m - Manual).",
                                       blank=False,
                                       default="m")
    auto_delegation_type = models.CharField(max_length=100,
                                            help_text="Automatic delegation "
                                                      "type.",
                                            blank=True,
                                            null=True)

    def get_absolute_url(self):
        return reverse("configuration_detail",
                       args=[str(self.name)])

    def __str__(self):
        return self.name


class Pool(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Pool name.",
                            primary_key=True)
    tier_class = models.ForeignKey(to='TierClass',
                                   on_delete=models.SET_NULL,
                                   null=True,
                                   blank=True)
    configuration = models.ForeignKey(to='Configuration',
                                      on_delete=models.CASCADE,
                                      default="default",
                                      editable=False)
    local_ip = models.GenericIPAddressField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("locus_detail",
                       args=[str(self.name)])

    class Meta:
        ordering = ["name"]


class TierClass(models.Model):
    configuration = models.ForeignKey(to='Configuration',
                                      on_delete=models.CASCADE,
                                      default="default",
                                      editable=False)
    name = models.CharField(max_length=50,
                            help_text="Tier name.")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("tierclass_detail",
                       args=[str(self.id)])


class Container(models.Model):
    pool = models.ForeignKey(to='Pool',
                             on_delete=models.SET_NULL,
                             blank=True,
                             null=True)
    name = models.CharField(max_length=100,
                            null=True,
                            blank=True)
    description = models.CharField(max_length=100,
                                   null=True,
                                   blank=True)
    pid = models.BigIntegerField(null=True,
                                 blank=True)
    status = models.CharField(max_length=20,
                              null=True,
                              blank=True)
    usage_memory = models.BigIntegerField(null=True,
                                          blank=True)
    usage_memory_peak = models.BigIntegerField(null=True,
                                               blank=True)
    usage_swap = models.BigIntegerField(null=True,
                                        blank=True)
    usage_swap_peak = models.BigIntegerField(null=True,
                                             blank=True)
    cpu_usage = models.BigIntegerField(null=True,
                                       blank=True)
    processes = models.IntegerField(null=True,
                                    blank=True)
    full_network_info = models.TextField(null=True,
                                         blank=True)
    created = models.DateTimeField(auto_now_add=True,
                                   editable=False)
    last_update = models.DateTimeField(auto_now_add=True,
                                       editable=False)

    def __str__(self):
        return self.name


class Image(models.Model):
    alias = models.CharField(max_length=50,
                             help_text="Tier name.",
                             unique=True)
    fingerprint = models.CharField(max_length=64,
                                   help_text="Tier name.",
                                   unique=True)

    def __str__(self):
        return self.alias

    class Meta:
        ordering = ["alias"]

server/webserver/monitor/models.py
from django.db import models


# CoLiSEU
class KPILink(models.Model):
    locus1 = models.ForeignKey(to='core.Pool',
                               on_delete=models.CASCADE)
    locus2 = models.ForeignKey(to='core.Pool',
                               related_name="locus2",
                               on_delete=models.CASCADE)
    jitter_1to2 = models.FloatField(help_text="Jitter from 1 to 2",
                                    blank=True,
                                    null=True)
    latency_max_1to2 = models.FloatField(help_text="Max Latency from 1 to 2",
                                         blank=True,
                                         null=True)
    latency_median_1to2 = models.FloatField(help_text="Median Latency "
                                                      "from 1 to 2",
                                            blank=True,
                                            null=True)
    latency_min_1to2 = models.FloatField(help_text="Min Latency from 1 to 2",
                                         blank=True,
                                         null=True)

    jitter_2to1 = models.FloatField(help_text="Jitter from 2 to 1",
                                    blank=True,
                                    null=True)
    latency_max_2to1 = models.FloatField(help_text="Max Latency from 2 to 1",
                                         blank=True,
                                         null=True)
    latency_median_2to1 = models.FloatField(
            help_text="Median Latency from 2 to 1",
            blank=True,
            null=True)
    latency_min_2to1 = models.FloatField(help_text="Min Latency from 2 to 1",
                                         blank=True,
                                         null=True)

    throughput = models.FloatField(help_text="Link Throughput",
                                   blank=True,
                                   null=True)
    timestamp = models.DateTimeField(auto_now_add=True,
                                     editable=False)

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ["timestamp"]


class KPIWireless(models.Model):
    locus = models.ForeignKey(to='core.Pool',
                              related_name="locus",
                              on_delete=models.CASCADE)
    mac = models.CharField(max_length=17,
                           blank=True,
                           help_text="MAC address", )
    mfb = models.BooleanField(default=False, help_text="")
    tdls = models.BooleanField(default=False, help_text="")
    wmm = models.BooleanField(default=False, help_text="")
    authenticated = models.BooleanField(default=False,
                                        help_text="Is authenticated?")
    authorized = models.BooleanField(default=False,
                                     help_text="Is authorized?")
    expected_throughput = models.CharField(max_length=10,
                                           blank=True,
                                           help_text="Expected link throughput")
    inactive_time = models.CharField(max_length=10,
                                     blank=True,
                                     help_text="Inactive time")
    preamble = models.CharField(max_length=10,
                                blank=True,
                                help_text="Preamble")
    rx_bitrate = models.CharField(max_length=20,
                                  blank=True,
                                  help_text="RX bitrate")
    rx_bytes = models.IntegerField(help_text="RX bytes")
    rx_packets = models.IntegerField(help_text="RX packets")
    signal = models.CharField(max_length=20,
                              blank=True,
                              help_text="Signal intensity")
    signal_avg = models.CharField(max_length=20,
                                  blank=True,
                                  help_text="Signal average")
    tx_bitrate = models.CharField(max_length=30,
                                  blank=True,
                                  help_text="TX bitrate", )
    tx_bytes = models.IntegerField(help_text="TX bytes")
    tx_failed = models.IntegerField(help_text="TX failed")
    tx_retries = models.IntegerField(help_text="TX retries")
    timestamp = models.DateTimeField(auto_now_add=True,
                                     editable=False)

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ["timestamp"]


# Experiment3.1
class KPICommand(models.Model):
    locus = models.ForeignKey(to='core.Pool',
                              on_delete=models.CASCADE)
    proc_time = models.FloatField(help_text="Processing time measurement",
                                  blank=True,
                                  null=True)
    response_time = models.FloatField(help_text="Response time measurement",
                                      blank=True,
                                      null=True)
    cmd = models.CharField(help_text="Command Issued",
                           max_length=200,
                           blank=True,
                           null=True)
    CMD_TYPE_CHOICES = (("v", "Voice"),
                        ("g", "Gesture"))
    cmd_type = models.CharField(max_length=1,
                                help_text="Command Type",
                                choices=CMD_TYPE_CHOICES,
                                blank=True,
                                null=True)
    timestamp = models.DateTimeField(auto_now_add=True,
                                     editable=False)

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ["timestamp"]


class KPIResources(models.Model):
    locus = models.ForeignKey(to='core.Pool',
                              on_delete=models.CASCADE)
    CPU = models.FloatField(help_text="CPU Load",
                            blank=True,
                            null=True)
    memory = models.FloatField(help_text="Memory usage",
                               blank=True,
                               null=True)
    timestamp = models.DateTimeField(auto_now_add=True,
                                     editable=False)

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ["timestamp"]

class KPILte(models.Model):
    locus = models.ForeignKey(to='core.Pool',
                              on_delete=models.CASCADE)
    dl_ri = models.FloatField(help_text="Download RI",
                            blank=True,
                            null=True)
    dl_bler = models.FloatField(help_text="Download BLER",
                            blank=True,
                            null=True)
    dl_mcs = models.FloatField(help_text="Download MCS",
                            blank=True,
                            null=True)
    dl_cqi = models.FloatField(help_text="Download CQI",
                            blank=True,
                            null=True)
    dl_brate = models.FloatField(help_text="Download Bit Rate",
                            blank=True,
                            null=True)
    
    ul_bler = models.FloatField(help_text="Upload BLER",
                            blank=True,
                            null=True)
    ul_mcs = models.FloatField(help_text="Upload MCS",
                            blank=True,
                            null=True)
    ul_snr = models.FloatField(help_text="Upload SNR",
                            blank=True,
                            null=True)
    ul_brate = models.FloatField(help_text="Upload Bit Rate",
                            blank=True,
                            null=True)
    ul_bsr = models.FloatField(help_text="Upload BSR",
                            blank=True,
                            null=True)
    ul_phr = models.FloatField(help_text="Upload PHR",
                            blank=True,
                            null=True)
    
    tx_gain = models.FloatField(help_text="TX Gain",
                            blank=True,
                            null=True)
    rx_gain = models.FloatField(help_text="RX Gain",
                            blank=True,
                            null=True)
    
    rnti = models.CharField(max_length=5,
                            blank=True,
                            help_text="RNTI")
    
    timestamp = models.DateTimeField(auto_now_add=True,
                                     editable=False)

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ["timestamp"]

class KPIOptical(models.Model):
    locus = models.ForeignKey(to='core.Pool',
                              on_delete=models.CASCADE)
    func_name = models.CharField(max_length=30,
                            blank=True,
                            help_text="Function name")
    port_number = models.IntegerField(help_text="Port number",
                            blank=True,
                            null=True)
    bits_in = models.IntegerField(help_text="Bits In",
                            blank=True,
                            null=True)
    bits_out = models.IntegerField(help_text="Bits Out",
                            blank=True,
                            null=True)
    total = models.IntegerField(help_text="Total Bits In/Out",
                            blank=True,
                            null=True)
    
    timestamp = models.DateTimeField(auto_now_add=True,
                                     editable=False)

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ["timestamp"]

server/webserver/core/templates/core/configuration_detail.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content_body %}
    <div class="container">
        <style>
            table, td {
                border: 1px solid black;
                padding: 5px;
                text-align: center;
            }
        </style>
        <p><strong>Delegation mode:</strong>
            {% if configuration.delegation_mode == 'a' %}
                Automatic{% elif configuration.delegation_mode == 'm' %}
                Manual{% endif %}</p>
        {% if configuration.delegation_mode == 'a' %}
            <p><strong>Automatic delegation
                type:</strong> {{ configuration.auto_delegation_type }}
            </p>{% endif %}

        <p><a href="{{ configuration.get_absolute_url }}/update/">Update
            configuration</a></p>
        <p><a href="{{ configuration.get_absolute_url }}/delete/">Delete
            configuration</a></p>

        <div style="margin-left: 20px;margin-top: 20px">
            <h4>Tier Classes</h4>
            {% for tierclass in configuration.tierclass_set.all %}
                <li><strong><a
                        href="{{ tierclass.get_absolute_url }}">{{ tierclass.name }}</a></strong>
                </li>
            {% endfor %}
            <li><a href="{% url 'tierclass_create' %}">+ Add new Tier Class</a>
            </li>
        </div>
        <hr>
        <div style="margin-left: 20px;margin-top: 20px">
            <h4>Pools</h4>
            <table>
                <tr>
                    <td><strong>Name</strong></td>
                    <td><strong>Tier Class</strong></td>
                </tr>
                {% for pool in configuration.pool_set.all %}
                    <tr>
                        <td>
                            <a href="{{ pool.get_absolute_url }}">{{ pool.name }}</a>
                        </td>
                        <td>
                            <a href="{{ pool.tier_class.get_absolute_url }}">{{ pool.tier_class.name }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <li><a href="{% url 'locus_create' %}">+ Add new Pool</a></li>

        </div>
    </div>
{% endblock %}

server/webserver/core/templates/core/configuration_form.html
{% extends 'base.html' %}
{% block content_body %}
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit"/>
        </form>
    </div>
{% endblock %}

server/webserver/core/templates/core/container_info.html
{% extends "base.html" %}
{% block title %}Container information{% endblock %}
{% block content_body %}
    <div class="container">
        <p>Information about container</p>
    </div>
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Basic information</div>
            <div class="panel-body">
                <b>Container name:</b> {{ container.name }}<br/>
                <b>Description:</b> {{ container.description }} <br/>
                <b>Status:</b> {{ container.status }}<br/>
                <b>Created at:</b> {{ container.created }}<br/>
                <b>PID:</b> {{ container.pid }}<br/>
                <b>Last update:</b> {{ container.last_update }}
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Memory</div>
            <div class="panel-body">
                <b>Usage:</b> {{ container.usage_memory }} <br/>
                <b>Usage peak:</b> {{ container.usage_memory_peak }} <br/>
                <b>Swap usage:</b> {{ container.usage_swap }} <br/>
                <b>Swap usage peak:</b> {{ container.usage_swap_peak }} <br/>
            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">CPU</div>
            <div class="panel-body">
                <b>Usage:</b> {{ container.cpu_usage }}<br/>
                <b>Processes:</b> {{ container.processes }}<br/>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Network</div>
            <div class="panel-body">
                {% for key, item in container.full_network_info.items %}
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3><b>Interface {{ key }}</b></h3> <br/>
                            {% for lkey, litem in item.items %}
                                <b>{{ lkey }}: </b>
                                {% if lkey == 'addresses' %} <br/>
                                    <ul class="list-group">
                                        {% for xitem in litem %}
                                            {% for elkey, elitem in xitem.items %}
                                                <li class="list-group-item">
                                                    <b>{{ elkey }}:</b>
                                                    {{ elitem }}
                                                </li>
                                            {% endfor %}
                                        {% endfor %}
                                    </ul>
                                {% elif lkey == 'counters' %} <br/>
                                    <ul class="list-group">
                                        {% for elkey, elitem in litem.items %}
                                            <li class="list-group-item">
                                                <b>{{ elkey }}:</b> {{ elitem }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    {{ litem }}
                                {% endif %}<br/>
                            {% endfor %}
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

server/webserver/core/templates/core/index.html
{% load staticfiles %}
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Containers ADMIN</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet"
          href="{% static 'core/plugins/libs/bootstrap-3.3.5/css/bootstrap.css' %}">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <link rel="stylesheet"
          href="{% static 'core/plugins/libs/bootstrap-3.3.5/css/bootstrap-theme.css' %}">
    <link rel="stylesheet"
          href="{% static 'core/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/css/main.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Containers</a>
        </div>
        <ul class="nav nav-pills">
            <li role="presentation" class="active"><a href="#">Home</a></li>
            <li role="presentation"><a href="#">Profile</a></li>
            <li role="presentation"><a href="#">Messages</a></li>
        </ul>
        <div id="navbar" class="navbar-collapse collapse"></div>
    </div>
</nav>
{% block content_body %}{% endblock %}
<center>
    FUTEBOL Project
</center>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}libs/jquery/2.1.0/jquery-2.1.0.min.js"><\/script>')</script>
<script src="{% static 'core/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'core/plugins/js/main.js' %}"></script>
</body>
</html>

server/webserver/core/templates/core/pool_detail.html
{% extends "base.html" %}
{% block title %}Locus Details{% endblock %}

{% block content_body %}
    <style>
        table, td {
            border: 1px solid black;
            padding: 5px;
            text-align: center;
        }
    </style>
    <p class="container">
    <h1>{{ pool }}</h1>
    <p><strong>Tier Class: </strong><a
            href="{{ pool.tier_class.get_absolute_url }}">{{ pool.tier_class.name }}</a>
    </p>

    <p><a href="{{ pool.get_absolute_url }}/update/">Update Locus Info</a></p>
    <p><a href="{{ pool.get_absolute_url }}/delete/">Delete Locus</a></p>

    <div style="margin-left: 20px;margin-top: 20px">
        <h4>KPI Link</h4>
        <table>
            <tr>
                <td rowspan="2"><strong> ID </strong></td>
                <td rowspan="2"><strong> Locus1 </strong></td>
                <td rowspan="2"><strong> Locus2 </strong></td>
                <td colspan="4"><strong> 1 -> 2 </strong></td>
                <td colspan="4"><strong> 2 -> 1 </strong></td>
                <td rowspan="2"><strong> Throughput </strong></td>
            </tr>
            <tr>
                <td><strong> Jitter </strong></td>
                <td><strong> Latency Max </strong></td>
                <td><strong> Latency Median </strong></td>
                <td><strong> Latency Min </strong></td>
                <td><strong> Jitter </strong></td>
                <td><strong> Latency Max </strong></td>
                <td><strong> Latency Median </strong></td>
                <td><strong> Latency Min </strong></td>
            </tr>
            {% for measurement in pool.kpilink_set.all %}
                <tr>
                    <td>{{ measurement.pk }}</td>
                    <td>{{ measurement.locus1 }}</td>
                    <td>{{ measurement.locus2 }}</td>
                    <td>{{ measurement.jitter_1to2 }}</td>
                    <td>{{ measurement.latency_max_1to2 }}</td>
                    <td>{{ measurement.latency_median_1to2 }}</td>
                    <td>{{ measurement.latency_min_1to2 }}</td>
                    <td>{{ measurement.jitter_2to1 }}</td>
                    <td>{{ measurement.latency_max_2to1 }}</td>
                    <td>{{ measurement.latency_median_2to1 }}</td>
                    <td>{{ measurement.latency_min_2to1 }}</td>
                    <td>{{ measurement.throughput }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div style="margin-left: 20px;margin-top: 20px">
        <h4>Command Measurements</h4>
        <table>
            <tr>
                <td><strong> ID </strong></td>
                <td><strong> Processing time </strong></td>
                <td><strong> Response time </strong></td>
                <td><strong> Command </strong></td>
                <td><strong> Command Type </strong></td>
            </tr>
            {% for measurement in pool.kpicommand_set.all %}
                <tr>
                    <td>{{ measurement.pk }}</td>
                    <td>{{ measurement.proc_time }}</td>
                    <td>{{ measurement.response_time }}</td>
                    <td>{% if measurement.cmd != '' %}
                        {{ measurement.cmd }}{% else %}Null{% endif %}</td>
                    <td>{% if measurement.cmd_type == 'v' %}
                        Voice{% elif measurement.cmd_type == 'g' %}
                        Gesture{% elif measurement.cmd_type == '' %}
                        Null{% else %}Invalid{% endif %}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    </div>
{% endblock %}

server/webserver/core/templates/core/pool_form.html
{% extends 'base.html' %}
{% block content_body %}
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit"/>
        </form>
    </div>
{% endblock %}

server/webserver/core/templates/core/tierclass_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Tier{% endblock %}
{% block content_body %}
    <div class="container">
        <p> Are you sure you want to delete the Tier class {{ tierclass }}?</p>

        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes, delete."/>
        </form>
    </div>
{% endblock %}

server/webserver/core/templates/core/tierclass_detail.html
{% extends "base.html" %}
{% block title %}TierClass Details{% endblock %}

{% block content_body %}
    <div class="container">
        <h1>{{ tierclass }}</h1>

        <p><a href="{{ tierclass.get_absolute_url }}/delete/">Delete
            TierClass</a></p>

        <div style="margin-left: 20px;margin-top: 20px">
            <h4>Locus</h4>

            {% for pool in tierclass.pool_set.all %}
                <hr>
                <p><strong>Name: </strong><a
                        href="{{ pool.get_absolute_url }}">{{ pool.name }}</a>
                </p>
            {% endfor %}
            <li><a href="{% url 'tier_locus_create' tierclass.pk %}">+ Add new
                Locus</a></li>

        </div>
    </div>
{% endblock %}

server/webserver/core/templates/core/tierclass_form.html
{% extends 'base.html' %}
{% block content_body %}
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit"/>
        </form>
    </div>
{% endblock %}